controller_manager_ns: /
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - move_x
      - move_y
      - turn
      - shoulder
      - elbow
      - another_elbow
      - wrist