controller_manager_ns: /
controller_list:
  - name: manipulator_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - move_rotate
    - move_forward
    - turn
    - shoulder
    - elbow
    - another_elbow