controller_list:
  - name: fake_manip_controller
    joints:
      - move_rotate
      - move_forward
      - turn
      - shoulder
      - elbow
      - another_elbow
initial:  # Define initial robot poses.
#  - group: manip
#    pose: home
